fraud:
  outputs:
    dev:
      account: PRVIMCA-IZ59979
      database: AIRBYTE_DATABASE
      password: snowflake
      role: AIRBYTE_ROLE
      schema: prod
      threads: 1
      type: snowflake
      user: AIRBYTE_USER
      warehouse: AIRBYTE_WAREHOUSE
  target: dev
