--- Use Admin role. Highest-privilege role in snowflake 
USE ROLE ACCOUNTADMIN;

--- Create 'transform' role and assign it to ACCOUNTADMIN
CREATE ROLE IF NOT EXISTS TRANSFORM;
GRANT ROLE TRANSFORM TO ROLE ACCOUNTADMIN;

--- Create default warehouse(Virtual)
CREATE WAREHOUSE IF NOT EXISTS COMPUTE_WH; --- Warehouse in Snowflake are compute clusters for running queries.
GRANT OPERATE ON WAREHOUSE COMPUTE_WH TO ROLE TRANSFORM;

--- Create the 'dbt' user and assign to the transform role
CREATE USER IF NOT EXISTS dbt 
    PASSWORD='dbtPassword123'
    LOGIN_NAME='dbt'
    MUST_CHANGE_PASSWORD=FALSE
    DEFAULT_WAREHOUSE='COMPUTE_WH'
    DEFAULT_ROLE=TRANSFORM
    DEFAULT_NAMESPACE='MOVIELENS.RAW'
    COMMENT='DBT user used for data transformation';
ALTER USER dbt SET TYPE= LEGACY_SERVICE; --- Seta the user as a service account.
GRANT ROLE TRANSFORM TO USER dbt;

--- Create a database and schema for the MovieLens project
CREATE DATABASE IF NOT EXISTS MOVIELENS;
CREATE SCHEMA IF NOT EXISTS MOVIELENS.RAW;

--- Grant permission to the 'transform' role
GRANT ALL ON WAREHOUSE COMPUTE_WH TO ROLE TRANSFORM;
GRANT ALL ON DATABASE MOVIELENS TO ROLE TRANSFORM;
GRANT ALL ON ALL SCHEMAS IN DATABASE MOVIELENS TO ROLE TRANSFORM;
GRANT ALL ON FUTURE SCHEMAS IN DATABASE MOVIELENS TO ROLE TRANSFORM;
GRANT ALL ON ALL TABLES IN SCHEMA MOVIELENS.RAW TO ROLE TRANSFORM;
GRANT ALL ON FUTURE TABLES IN SCHEMA MOVIELENS.RAW TO ROLE TRANSFORM;